name: Check version

on:
  push:
    branches:
      - master

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed file names
        id: changed-files
        run: |
          echo "::set-output name=yamls::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep .yaml$ | xargs)"
      - name: Test print
        run: |
          echo "hello github actions"