name: Check version

on:
  push:
    branches:
      - master
    paths:
      - "package_b/**"

jobs:
  publish-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Project
        run: yarn install --frozen-lockfile
        working-directory: ./package_b/

      - name: Publish
        run: npm publish
        working-directory: ./package_b/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}