name: Check version

on:
  push:
    branches:
      - master
    paths:
      - "package_b/**"

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - run: |
          npm ci
          npm publish
        working-directory: ./package_b/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}